version: '3.8'

services:
  backend:
    build: ./backend
    container_name: safesphere-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/safesphere
      - JWT_SECRET=supersecretkey
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    container_name: safesphere-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15
    container_name: safesphere-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=safesphere
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  postgres_data:
